### ISSUE TITLE
Trac deprecation notice should mention migration policy

### ISSUE THREAD

**Issue by tonyelewis** [boostorg/boost#191]
Thanks for the deprecation notice at the top Boost Trac page ([here](https://svn.boost.org/trac10#WelcometotheBoostTrac)).

IMO, the body of live Boost tickets on Trac is a very important resource.

I think the deprecation notice should have at least one more sentence to describe the proposed policy for migrating live Trac tickets to GitHub. Are reporters expected to manually migrate their live tickets over? Or are library maintainers going to do that? Or will it happen automatically? Or are library maintainers expected to continue working through old Trac tickets on Trac?

Thanks.

<sub>(Apologies if this isn't the best repo to have raised this issue against.)</sub>

**Comment by Mike-Devel** [comment]
I think the discussion on the ML ended with the expectation that each library author is responsible to migrate the tickes him/herself if so desired. I think there isn't really an "official" boostwide policy.

**Comment by mjcaisse** [comment]
Updated the comment at the top of Trac to reflect the "policy".

**Comment by tonyelewis** [comment]
Great - thanks very much for this.
