### ISSUE TITLE
Where is file boost/project-config.jam?

### ISSUE THREAD

**Issue by tiendq** [boostorg/boost#200]
This [cheatsheet](https://github.com/boostorg/boost/wiki/Getting-Started-Cheat-Sheet) mentions about file `project-config.jam` in setup steps but I didn't find this file.

> In project-config.jam, set the libraries = line to read libraries = --with-date_time ;

**Comment by swatanabe** [comment]
AMDG

On 10/03/2018 10:18 PM, Tien Do wrote:
> This [cheatsheet](https://github.com/boostorg/boost/wiki/Getting-Started-Cheat-Sheet) mentions about file `project-config.jam` in setup steps but I didn't find this file.
> 

It's created by booststrap.sh.  The steps
shown are in the wrong order.

>> In project-config.jam, set the libraries = line to read libraries = --with-date_time ;
> 

In Christ,
Steven Watanabe

**Comment by tiendq** [comment]
Thanks, it works now. I have also updated the cheatsheet steps with correct order.
