### ISSUE TITLE
GitHub releases contain empty archives

### ISSUE THREAD

**Issue by Kojoley** [boostorg/boost#215]
I have downloaded a 1.55 tarball from GitHub releases page and it contains mostly empty folders (it looks like submodules were not fetched/checkouted before archiving). Then I checked 1.68 and it is the same situation.

**Comment by jeking3** [comment]
They are automatically generated by GitHub, I'm not sure one can disable that.

**Comment by Kojoley** [comment]
I missed that those tarballs are auto-generated by GitHub. It is so misleading...
