### ISSUE TITLE
Boost directory iterator not working with Windows virtual hard disks ?

### ISSUE THREAD

**Issue by kenkit** [boostorg/boost#217]
I've experienced the above bug on windows x86 using latest boost.

The said code is below
`  for (boost::filesystem::recursive_directory_iterator end,
         dir(path(file_name));
         dir != end; ++dir) `
I was initially using ` dir(file_name);` when I discovered this.
The error occured only when scanning root drive. ie `F:\ `

**Comment by mclow** [comment]
You should probably report this against Boost.Filesystem; it will get more attention there.
https://github.com/boostorg/filesystem

**Comment by jeking3** [comment]
@kenkit you can close this issue here if it was moved to the right repo.   Thanks.

**Comment by kenkit** [comment]
ok, thanks
