### ISSUE TITLE
boost program options: win64: bcp namespace renamed version: *.lib file of program_options for *.dll is not created

### ISSUE THREAD

**Issue by mrbachmann** [boostorg/boost#220]
Between boost 1.63.0 and 1.65.1 line 12 of file 'libs/program_options/build/Jamfile.v2' has been changed as follows:

from:
12: lib boost_program_options

to:
12: boost-lib program_options

This change is the reason why in a bcp'ed version of the sources the *.lib file for the program_options *.dll file is not created e.g. on win64/win32, because:

The target name stays unchanged after bcp namespace rename:
12: boost-lib program_options

however it should read in the bcp'ed version:
12: lib boost_1_65_1_program_options

Please apply the following patch to fix the problem:
```
-------------------------------------------------------------------------------
diff -ruN boost_1_65_1.orig/libs/program_options/build/Jamfile.v2 boost_1_65_1/libs/program_options/build/Jamfile.v2
--- boost_1_65_1.orig/libs/program_options/build/Jamfile.v2	2018-11-20 15:18:48.469951300 +0100
+++ boost_1_65_1/libs/program_options/build/Jamfile.v2	2018-11-20 15:19:25.860690000 +0100
@@ -9,8 +9,8 @@
     convert winmain split
     ;
 
-boost-lib program_options
+lib boost_program_options
     : $(SOURCES).cpp
     : # See https://svn.boost.org/trac/boost/ticket/5049
       <target-os>hpux,<toolset>gcc:<define>_INCLUDE_STDC__SOURCE_199901
-    ;
\ No newline at end of file
+    ;
-------------------------------------------------------------------------------

```

**Comment by mclow** [comment]
This will get more attention if it is attached to the Boost.ProgramOptions repo, which is here: https://github.com/boostorg/program_options

**Comment by mrbachmann** [comment]
Thanks for the hint!
opened a new issue under:
=> https://github.com/boostorg/program_options/issues/66

Closing this issue...
