### ISSUE TITLE
ublas abandoned?

### ISSUE THREAD

**Issue by iljah** [boostorg/boost#233]
Ublas seems to be unmaintained for over a year now, at least judging by pull requests being ignored for what looks like clear bug(s): https://github.com/boostorg/ublas/pull/50

"Development" repo mentioned in boostorg/ublas readme hasn't been updated in 3 years: https://github.com/uBLAS/ublas

Does ublas not have a (backup) maintainer anymore (either)?

**Comment by magictiger** [comment]
It looks like uBlas has been moved under libs/numeric, please see https://github.com/boostorg/boost/tree/master/libs/numeric

**Comment by iljah** [comment]
That link does not have any code. As far as I can tell, above and other git links point to https://github.com/boostorg/ublas/ Development seems to have picked up again in last couple of months so I guess this can be closed.
