### ISSUE TITLE
Add a README.md

### ISSUE THREAD

**Issue by thefreakingmind12** [boostorg/boost#238]

**Comment by jxu** [comment]
https://github.com/boostorg/boost/blob/master/index.html and https://www.boost.org/ but I agree

**Comment by divyanshu132** [comment]
Can I work on this??

**Comment by jxu** [comment]
Looks like development happens on mailing lists, so ask there.
https://www.boost.org/community/ 
https://www.boost.org/community/groups.html#main

**Comment by thefreakingmind12** [comment]
@divyanshu132  Go Ahead and add that. It will be a Good Addition for New People to Start Contributing. Although refer to https://github.com/boostorg/boost/blob/master/index.html for adding. as @jxu suggested this is already there but a small README will be useful.

**Comment by shubhamofbce** [comment]
is this issue still open?? Can i work on it @thefreakingmind12

**Comment by mohitm15** [comment]
@thefreakingmind12 Can you clarify what you require in the readme file?? or  just to add only a readme file

**Comment by mohitm15** [comment]
@thefreakingmind12 please review https://github.com/boostorg/boost/pull/260

**Comment by thefreakingmind12** [comment]
@mohitm15 Added the comment on your PR. Please get that done. Thanks.

**Comment by glenfe** [comment]
A README already exists, and is sufficient.
