### ISSUE TITLE
Isolating required modules at bootstrap.sh

### ISSUE THREAD

**Issue by Dravion** [boostorg/boost#239]
Hi,
I use BOOST, thanks for this great peace of Software!

But i think the Build Documentation should cover Minimal builds as well. Its a  pain to built each and everything  for any Setup (Debug/Release, diffrent archl diffrent OS, diffrent Compiler ect) and it
would be cool if there is an tutorial which covers the step necessary to build user specific boost 
instead of the whole thing. Such a Guide should also cover howto extend modules, which where
not build at the initial build so its possible to rerun the build process of an existing allready
builded BOOST build and only add specific modules and nothing else.

**Comment by Dravion** [comment]
If found a way on Stackoverflow https://stackoverflow.com/questions/10022180/how-to-build-boost-required-modules-only

For Visual Studio 2017 i use this for selective builds
#Win32 
b2 toolset=msvc-14.1 --build-dir=build --stagedir=out32 --with-filesystem --with-regex --with-thread
#Win64
b2 toolset=msvc-14.1 --build-dir=build address-model=64 --stagedir=out64 --with-filesystem --with-regex --with-thread

I took about 4 Minutes instead of 20 Minutes to build.

**Comment by tiendq** [comment]
Building selective libs are already instructed [here](https://github.com/boostorg/boost/wiki/Getting-Started%3A-Cheat-Sheet#list-of-steps).
