### ISSUE TITLE
 error: use of deleted function

### ISSUE THREAD

**Issue by mahuichao** [boostorg/boost#274]
I have a class **PhoneExtractor**,the header file like:
`class PhoneExtractor{
        public:
                PhoneExtractor(){}
                PhoneExtractor(string conf_file_name);
                //PhoneExtractor();
                ~PhoneExtractor();
}`
I use boost python,the file like:
`using namespace boost::python;

BOOST_PYTHON_MODULE(libextractor)
{
        class_<PhoneExtractor>("PhoneExtractor",init<std::string>())
        .def("chainDecode", &PhoneExtractor::chainDecode)
        ;
}`

But I got error:

> /home/mahch/workspace/dep/lib/include/boost/python/object/value_holder.hpp:133:13: error: use of deleted function ‘PhoneExtractor::PhoneExtractor(const PhoneExtractor&)’
             BOOST_PP_REPEAT_1ST(N, BOOST_PYTHON_UNFORWARD_LOCAL, nil)

I don't know where I am wrong,can you help me ?

**Comment by prajwaljpj** [comment]
@mahuichao I'm facing the same error. Did you find a way to solve this?
