### ISSUE TITLE
Does Boost instance the class when I compile the project

### ISSUE THREAD

**Issue by mahuichao** [boostorg/boost#275]
I came across a problem ,Because some reason,the class a can't be instance directly,so when I use boost ,there always an error.But if I let class b to include a variable of class a ,I can compile it with no error,so,I wonder,if Boost instance the class I want to expose or not?
Thanks

**Comment by swatanabe** [comment]
AMDG

I don't understand the question.
- The grammar is at the level of being nearly unintelligible.
- You don't indicate which Boost library you are trying to use.
- I have no idea what you mean by "instance."

In Christ,
Steven Watanabe

**Comment by mahuichao** [comment]
never mind ,still thanks.
