### ISSUE TITLE
Query: Available Performance modules in Boost

### ISSUE THREAD

**Issue by mayadav1** [boostorg/boost#297]
I am trying to benchmark boost on Windows with different compilers. Does boost has some standard benchmark that i can run and see the performance?

**Comment by mclow** [comment]
I think you'll get more responses on the boost-users mailing list (https://lists.boost.org/mailman/listinfo.cgi/boost-users) than here.

**Comment by swatanabe** [comment]
AMDG

On 5/29/19 11:38 PM, mayadav1 wrote:
> I am trying to benchmark boost on Windows with different compilers. Does boost has some standard benchmark that i can run and see the performance?
> 

No.  Some individual libraries do, though.

In Christ,
Steven Watanabe

**Comment by mayadav1** [comment]
can you  list down those individual libraries and way of use.

Kind Regards,
Manoj Kumar
