### ISSUE TITLE
how to drill down into libs?

### ISSUE THREAD

**Issue by Tagar** [boostorg/boost#311]
https://github.com/boostorg/boost/tree/master/libs

shows directories as non-clickable objects 

![image](https://user-images.githubusercontent.com/3013418/61269818-fa51b780-a75c-11e9-8fbe-50c7a2f0d839.png)

what do I miss? how to drill down into those directories?

thanks.

**Comment by mclow** [comment]
A better place for questions like this is the boost-users mailing list (boost-users@lists.boost.org). For a quick answer, though - each library has it's own repo. So, you can find Boost.Any at https://github.com/boostorg/any/tree/master/

**Comment by Tagar** [comment]
Thank you @mclow
