### ISSUE TITLE
Unable to Download Release Binaries

### ISSUE THREAD

**Issue by san4d** [boostorg/boost#375]
When I try to download any of the links from https://dl.bintray.com/boostorg/release/1.72.0/source/, I see a "Forbidden!" message. I also see this for 1.70.

Steps to reproduce:
```
$ curl -O https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.bz2
$ cat boost_1_72_0.tar.bz2
```

**Comment by jabaa** [comment]
I think it's a duplicate of https://github.com/boostorg/boost/issues/299. You can use https://sourceforge.net/projects/boost/files/boost/1.72.0/boost_1_72_0.tar.bz2 as a temporary solution

**Comment by san4d** [comment]
Thanks. I didn't see that issue. I'm able to download form the site.

**Comment by kszucs** [comment]
I'm experiencing the same, so the issue is valid:

```bash
✖ wget https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.bz2
--2020-03-01 10:39:53--  https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.bz2
Resolving dl.bintray.com (dl.bintray.com)... 52.28.187.224, 52.29.129.139
Connecting to dl.bintray.com (dl.bintray.com)|52.28.187.224|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-03-01 10:39:54 ERROR 403: Forbidden.
```
