### ISSUE TITLE
POSIX-compliance of Boost library

### ISSUE THREAD

**Issue by magnusmusngi** [boostorg/boost#419]
I am planning to port a code that uses this Boost library into a POSIX-compliant OS that is neither Linux nor Unix. Given this, I would like to know if this library is POSIX-compliant, and if so, does that mean that I will not have any issues with this library while porting it to the aforementioned OS? Thank you.

**Comment by mclow** [comment]
Boost is a collection of over 130 different libraries. Many are POSIX compliant, but some are not.
A better place to ask your question is on the boost-users mailing list (boost-users@lists.boost.org)
