### ISSUE TITLE
No regression testing against NVCC compiler

### ISSUE THREAD

**Issue by dahubley** [boostorg/boost#475]
We have an application involving realtime processing that uses boost and CUDA. CUDA is a great way to leverage the computing power of GPUs for numerical calculations. I have found that boost and CUDA do not play well together resulting in warnings and sometimes in build issues. I now realize that this is likely because there is not regression testing on the NVCC compilers from nvidia. Is there any interest in running these tests or is ours a completely unique use case?

**Comment by mclow** [comment]
All of our testing is done on a volunteer basis. I'm sure the library authors would welcome someone running an NVCC testing instance.   Docs are here: https://www.boost.org/development/running_regression_tests.html
