### ISSUE TITLE
missing package metadata in boost_1_75_0.tar.gz

### ISSUE THREAD

**Issue by VirenderNayal** [boostorg/boost#479]
I was trying to use boost libraries, 
I downloaded the boost_1_75_0.tar.gz package from the official website of boost.org.

When i tried to install the package it gives error:

![image](https://user-images.githubusercontent.com/72212823/108520362-9906a880-72f0-11eb-8419-4960d0c352f9.png)

I am using Endeavour OS (Arch Based).

**Comment by flyingcakes85** [comment]
That link downloads the source of boost. To install it using `pacman` you need to write a PKGBUILD.

A lot more easier method should be to install it from package repos.

For runtime, install `boost-libs`

```
sudo pacman -S boost-libs
```

For development, install `boost`

```
sudo pacman -S boost
```
