### ISSUE TITLE
general query

### ISSUE THREAD

**Issue by yashpalgoyal1304** [boostorg/boost#489]
hi,

i was just digging in recent updates history of my Win 10 20H2 update. and found this repo following the trail (in reverse order):
https://github.com/boostorg/boost
<-- https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE2Jy2l
<-- https://www.microsoft.com/en-us/wdsi/defenderupdates or https://go.microsoft.com/fwlink/?linkid=2007160
<-- ![image](https://user-images.githubusercontent.com/19423063/110367262-7523c080-806d-11eb-81d0-845bb1461d68.png)

so, i was thinking what role does this play there?

**Comment by mclow** [comment]
A much better place to ask this is on the boost-users mailing list: boost-users@lists.boost.org.  Many more people will see it there.
