### ISSUE TITLE
Migrate away from bintray.com services since it's shutting down

### ISSUE THREAD

**Issue by lhotari** [boostorg/boost#499]
The download links on https://www.boost.org/users/download/ use dl.bintray.com for downloads.

On https://bintray.com/boostorg page there's a large banner:
"Attention: All Bintray services will be deprecated and your accounts will be disabled on May 1st 2021."
this links to https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter

It is necessary to migrate away from bintray.com services before the shutdown. The schedule is explained in the link above.

**Comment by mclow** [comment]
Yes; we are working on an alternative. When we have something to announce, it will be on the website and the mailing lists.
