### ISSUE TITLE
boost_1_72_0.tar.bz is forbidden

### ISSUE THREAD

**Issue by john-wilkes** [boostorg/boost#530]
Same problem as #299.

$ wget https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.bz2
--2021-06-28 06:12:20--  https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.bz2
Resolving dl.bintray.com (dl.bintray.com)... 34.223.170.36, 50.112.35.45, 52.40.89.93, ...
Connecting to dl.bintray.com (dl.bintray.com)|34.223.170.36|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-06-28 06:12:21 ERROR 403: Forbidden.

**Comment by mclow** [comment]
Please see the announcement at https://www.boost.org/users/news/boost_has_moved_downloads_to_jfr.html
