### ISSUE TITLE
Boost library linking error

### ISSUE THREAD

**Issue by ishanshLal-tRED** [boostorg/boost#559]
LINK : fatal error LNK1104: cannot open file 'libboost_thread-vc142-mt-gd-x32-1_77.lib'

Using Visual Studio 2019 16.11.2

I have build libraries correctly the problem is b2 build tool is building version v1.78 instead of v1.77 (released version is actually required by the linker).

so how do i build v1.77 instead of v1.78 or how do tell linker to use v1.78 instead of  v1.77

**Comment by mclow** [comment]
You start with the 1.77.0 sources, not the current set from GitHub.  Download them from https://boostorg.jfrog.io/ui/native/main/release/1.77.0/source/

**Comment by ishanshLal-tRED** [comment]
😐 well is there really not a better way

**Comment by ishanshLal-tRED** [comment]
than downloading everytime i wanna update boost version

**Comment by mclow** [comment]
Sure. Fix your build system to link with whatever version of boost you're using. It changes about every four months.

**Comment by ishanshLal-tRED** [comment]
with BOOST_VERSION ?

**Comment by ishanshLal-tRED** [comment]
yup with #define BOOST_VERSION 107800 
&
#define BOOST_LIB_VERSION "1_78"
