### ISSUE TITLE
7z version of the current sources contain a directory with a garbled name

### ISSUE THREAD

**Issue by jrmoore** [boostorg/boost#625]
Not important or breaking, but the current source distribution has a directory with UTF-8 characters outside of the usual range that ended up being misinterpreted when archived to 7z.

It's in `libs\wave\test\testwave\testfiles`, the directory is supposed to be named `utf8-test-ßµ™∃`, but inside of the archive it's something like `utf8-test-ÃÂµâ¢â`

Maybe the way that archive is created should be revised, the rest are fine, zip and tar.*. I tried archiving in Windows in case it was a 7-Zip problem, but it seems to work as expected.

**Comment by sdarwin** [comment]
Hi @jrmoore, this might already be fixed, did you try with _latest_ snapshot, being the develop branch of boostorg/boost?  Here are the download links: https://boostorg.jfrog.io/artifactory/main/develop/

**Comment by jrmoore** [comment]
Thanks @sdarwin, the current snapshot is packaged as expected, I'm closing the issue already 😉.
