### ISSUE TITLE
command ./b2 install missing library :(

### ISSUE THREAD

**Issue by gesangtome** [boostorg/boost#632]
Build platfrom: fedora 35
source: boost 1.78.0

Here is the RPMSPEC I am using: [boost.spec.zip](https://github.com/boostorg/boost/files/8190404/boost.spec.zip)

No errors occurred during compilation, But the following libraries are not installed where I want.
libboost_stacktrace_basic.so.1.78.0 and libboost_fiber.so.1.78.0.

**Comment by rodgert** [comment]
I currently working on updating the boost package for [Fedora 37](https://fedoraproject.org/wiki/Changes/F37Boost178). If I just pull the release tarballs of boost_1_77_0 and boost_1_78_0 and build each outside of the fedpkg tooling, boost_1_77_0/stage/lib has the libraries but boost_1_78_0 does not.

**Comment by rodgert** [comment]
The issue is  not unique to Fedora, happens on Ubuntu 21.10 with a 'plain' ./bootstrap.sh && ./b2 of boost_1_78_0

**Comment by mclow** [comment]
See https://github.com/bfgroup/b2/issues/104

**Comment by rodgert** [comment]
Applying https://github.com/bfgroup/b2/commit/78fd284a42caabe8815cb0870b46e5567872e75b.patch addresses the problem, will add the patch to the Fedora boost.spec.

@mclow Thanks for the pointer!

**Comment by gesangtome** [comment]
@rodgert Excited, let me try.
