### ISSUE TITLE
Boost removing old revisions from Conan?

### ISSUE THREAD

**Issue by HeinanCA** [boostorg/boost#636]
Hey,
I'm looking for some guidelines on when is Conan removing old revisions of Boost?

Specifically, I'm now using 1.69 and trying to understand when is this version supposed to be removed?

**Comment by mclow** [comment]
Our general policy is not to remove old releases.
If you look at https://sourceforge.net/projects/boost/files/boost/ (which is where we used to put releases), you can see releases back to 1.20.
