### ISSUE TITLE
boost stacktrace and fiber libraries are missing when building 1.78.0 from source

### ISSUE THREAD

**Issue by nknadim1** [boostorg/boost#646]
Hi,

I am trying to build Boost 1.78.0 from source in Linux but have noticed that the stacktrace and fiber libraries are missing. I am using the following command to build boost.
bootstrap.sh
b2 -j8 --build-dir=/opt/disk1/boost/boost_build --prefix=/opt/disk1/boost_install/ --without-python address-model=64 toolset=gcc threading=multi variant=release install

I couldn't see any error in the log as well. So other libraries apart from these are building fine. I am using GCC 7.2.0 compiler, I tried with intel 2022 compiler as well but no luck.

Please suggest if I am missing something here.

Thanks.

**Comment by mclow** [comment]
Even better: https://github.com/bfgroup/b2/issues/104

**Comment by nknadim1** [comment]
Ok, I will try 1.79.0

Thanks.
