### ISSUE TITLE
support sendmmsg and recvmmsg

### ISSUE THREAD

**Issue by zkas** [boostorg/boost#650]
is there an plan to support sendmmsg and recvmmsg on unix platform? or WSARecvMsg on windows platform?

**Comment by mclow** [comment]
Which boost library are you referring to here?

**Comment by zkas** [comment]
> Which boost library are you referring to here?

boost_1_76_0, i searched the source code with visual studio code, but not found any keywords likes "sendmmsg" or "recvmmsg"

**Comment by mloskot** [comment]
@zkas Boost is a **collection of libraries**, so once again: Which Boost library you aim with your suggestion?

**Comment by zkas** [comment]
> @zkas Boost is a **collection of libraries**, so once again: Which Boost library you aim with your suggestion?

asio network, i also searched boost_1_79_0, but not found too.we need "sendmmsg" or "recvmmsg" to realize 
aggregate sending and receiving data through udp socket

**Comment by mloskot** [comment]
@zkas 
> asio network,

👉  https://github.com/chriskohlhoff/asio

> we need "sendmmsg" or "recvmmsg" to realize aggregate sending and receiving data through udp socket

Then, speak to Asio developers, not the whole Boost community.

**Comment by zkas** [comment]
thank you for your replay
