### ISSUE TITLE
Boost built and ready for iOS/macOS (repo)

### ISSUE THREAD

**Issue by blazorin** [boostorg/boost#668]
### I've made a [repository](https://github.com/blazorin/EssentialLibs) which contains Boost and OpenSSL built and ready for iOS and macOS architectures.

**Includes thread-safe libraries aswell!**

If possible, do not close this issue, just trying to help!

**Comment by mclow** [comment]
Rather than an issue; this would get more attention if you posted it to the boost-users mailing list (boost-users@lists.boost.org)

**Comment by blazorin** [comment]
> ([boost-users@lists.boos](mailto:boost-users@lists.boost.org)

I will send it there aswell! Didn't know about it. Thanks.
