### ISSUE TITLE
poly to mask

### ISSUE THREAD

**Issue by yulinhuyang** [boostorg/boost#698]
how to convert poly to mask using boost?

**Comment by mclow** [comment]
This is not a bug report; this is a request for information.
A better place to ask this is on the boost-users mailing list [boost-users@lists.boost.org](mailto:boost-users@lists.boost.org).
The subscription page for the list is at: https://lists.boost.org/mailman/listinfo.cgi/boost-users

In your email, be sure to mention which boost library you are using.
