### ISSUE TITLE
CMake Error at CMakeLists.txt:20 (include):   include could not find requested file:      BoostRoot

### ISSUE THREAD

**Issue by brendoncdrew** [boostorg/boost#716]
bdrew@HpEE:~/source/boost$ cmake ./
-- The CXX compiler identification is GNU 12.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:20 (include):
  include could not find requested file:

    BoostRoot

-- Configuring incomplete, errors occurred!
See also "/home/bdrew/source/boost/CMakeFiles/CMakeOutput.log".

**Comment by brendoncdrew** [comment]
RTFM

**Comment by excitoon** [comment]
Is there any solution to this?

**Comment by excitoon** [comment]
@brendoncdrew you probably keep it in some hidden branch, can you point us out?
