### ISSUE TITLE
Is Boost 1.83.0 really released?

### ISSUE THREAD

**Issue by ncook-hxgn** [boostorg/boost#792]
I have just been notified by GitHub that 1.83.0 has been released, however, the Boost.org website only mentions a beta 1: https://www.boost.org/users/history/version_1_83_0.html

The releases page here on GitHub does not provide a checksum for the source archive, so I'll be waiting for 1.83.0 to appear on the boost.org website, as our build process verifies this checksum.

Are any patches expected for 1.83.0?

**Comment by mclow** [comment]
The boost website has been updated; https://www.boost.org/users/history/version_1_83_0.html
There are patches available for Boost.JSON.

**Comment by mclow** [comment]
BTW, I suspect that GitHub notified you that 1.83 had been tagged (not released).  If it said "released", that's a mistake by Github.

**Comment by ncook-hxgn** [comment]
> BTW, I suspect that GitHub notified you that 1.83 had been tagged (not released). If it said "released", that's a mistake by Github.

It was quite heavy on the word release, aye:
![image](https://github.com/boostorg/boost/assets/36889813/772dc903-63f0-4d50-b4ce-ba2baa266de7)
![image](https://github.com/boostorg/boost/assets/36889813/f819e02d-a7ae-4c4c-a415-f5f35a758aa2)
