### ISSUE TITLE
boost-1.84.0.beta1: New library Cobald is not installed by CMake

### ISSUE THREAD

**Issue by bebuch** [boostorg/boost#834]
When I configure, build and install via CMake then Cobald is missing in the installed files. The other new library redis is installed correctly.

I downloaded from: https://github.com/boostorg/boost/releases/download/boost-1.84.0.beta1/boost-1.84.0.beta1.7z

**Comment by pdimov** [comment]
Using what compiler and what platform?

**Comment by klemens-morgenstern** [comment]
Which c++ standard did you compile with?

**Comment by bebuch** [comment]
C++20, I can post the full command line calls later if this helps.

Klemens Morgenstern ***@***.***> schrieb am Mi., 29. Nov.
2023, 07:10:

**Comment by bebuch** [comment]
I found the problem:

```
-- Boost.Cobalt: not building, the lowest supported MSVC version is 1930.  1929 is not supported
```

I use a VS 2019 x64 cmd command line. Directory structure:

```
C:/Temp/boost-1.84.0.beta1
C:/Temp/boost-build
C:/Temp/boost-install
```

```batch
cd C:/Temp/boost-1.84.0.beta1
cmake "-GNinja" "-DCMAKE_CXX_STANDARD=20" "-DCMAKE_INSTALL_PREFIX=C:\Temp\boost-install" "C:\Temp\boost-1.84.0.beta1"
cmake --build .
cmake --install .
```
