### ISSUE TITLE
Error on download files from JFrog - account deactivated

### ISSUE THREAD

**Issue by rafaels-dev** [boostorg/boost#842]
Today I'm trying to install the boost using the below podspec (extracted from react-native), but I was receiving the error message `[!] Error installing boost
Verification checksum was incorrect, expected f0397ba6e982c4450f27bf32a2a83292aba035b827a5623a14636ea583318c41, got 5e89103d9b70bba5c91a794126b169cb67654be2051f90cf7c22ba6893ede0ff`:.

PodSpec:
```podspec
# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

Pod::Spec.new do |spec|
  spec.name = 'boost'
  spec.version = '1.76.0'
  spec.license = { :type => 'Boost Software License', :file => "LICENSE_1_0.txt" }
  spec.homepage = 'http://www.boost.org'
  spec.summary = 'Boost provides free peer-reviewed portable C++ source libraries.'
  spec.authors = 'Rene Rivera'
  spec.source = { :http => 'https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.bz2',
                  :sha256 => 'f0397ba6e982c4450f27bf32a2a83292aba035b827a5623a14636ea583318c41' }

  # Pinning to the same version as React.podspec.
  spec.platforms = { :ios => '11.0' }
  spec.requires_arc = false

  spec.module_name = 'boost'
  spec.header_dir = 'boost'
  spec.preserve_path = 'boost'
end

```
When I try to open the URL https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.bz2 on the browser, I noticed the following page:
<img width="1431" alt="image" src="https://github.com/boostorg/boost/assets/5066597/f7d677b4-d5f0-4b89-a0e6-5dc4ff7e8f94">

I also download the same URL using the cURL and the result was a HTML page with the same SHA256 of the error message:
```sh
$ curl -L https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.bz2 | sha256sum
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   138  100   138    0     0    223      0 --:--:-- --:--:-- --:--:--   225
100 11534  100 11534    0     0   8325      0  0:00:01  0:00:01 --:--:--  8325
5e89103d9b70bba5c91a794126b169cb67654be2051f90cf7c22ba6893ede0ff  -
```

**Comment by jnak** [comment]
Same here!

**Comment by mina4gerges** [comment]
when it will be resolved ?

**Comment by irisjae** [comment]
Does anyone know of a mirror?

**Comment by rafaels-dev** [comment]
> Does anyone know of a mirror?

I downloaded a copy of the file hosted on Source Forge and put it directly on my project.
https://sourceforge.net/projects/boost/files/boost/1.76.0/

The SHA256 of the Source Forge file is the same as the original file.

**Comment by amadou1998** [comment]
same problem!

**Comment by danidaryaweesh** [comment]
Same problem for us too. Is this going to be fixed by them anytime soon?

**Comment by f4exb** [comment]
Same problem here too: https://github.com/f4exb/sdrangel/actions/runs/7372158552

**Comment by sdarwin** [comment]
> account deactivated.

A temporary mirror site: https://archives.boost.io/release/1.84.0/source/

Hopefully the jfrog links will be restored soon.

**Comment by irisjae** [comment]
Seems the links are back up.

**Comment by shamas** [comment]
> > Does anyone know of a mirror?
> 
> I downloaded a copy of the file hosted on Source Forge and put it directly on my project. https://sourceforge.net/projects/boost/files/boost/1.76.0/
> 
> The SHA256 of the Source Forge file is the same as the original file.

How did you put it directly in your project?

**Comment by Shigbeard** [comment]
This issue should be re-opened, at the time of writing the jfrog urls on the boost.org website lead to a landing page to "reactivate the account".

**Comment by MrCyjaneK** [comment]
I agree with @Shigbeard, all download links are broken as for now

**Comment by MrCyjaneK** [comment]
@userdocs yet it is the official link from the official website

**Comment by qidaye** [comment]
jfrog is still not working.
