### ISSUE TITLE
Troubles with Install Boost.Build

### ISSUE THREAD

**Issue by Bolehlaf** [boostorg/boost#904]
Hello, 
we are trying to run this python library: https://pypi.org/project/ur-rtde/ and it listed Boost as its dependency. According to guide, we were supposed to install boost build. We were following the documentation: https://www.boost.org/doc/libs/1_85_0/more/getting_started/windows.html#install-boost-build
Unfortunately, when we ran step 3: Run b2 install --prefix=our/path, in the result was not /bin folder, so we couldn't add it to PATH environment variables. We deleted this folder and tried to run this command again, but there was even less files and again without /bin folder.
Do you have any suggestions, what could we do wrong?

**Comment by nghia1303** [comment]
@Bolehlaf I have the same issue, have you found the solution yet? I've struggled for days

**Comment by Bolehlaf** [comment]
@nghia1303 I'm not sure, how we managed to resolve this, but if I remember correctly, out final workaround wast that we installed whole Boost library, not just boost build. Try it that way and if it doesn't work, let me know. I will try to recreate the problem and maybe I will recall our solution 😅

**Comment by nghia1303** [comment]
@Bolehlaf Thanks for reply, I fixed my issue, mine was because of the square brackets in the path leads to boost lib, so b2 cannot process the path correctly. I changed the boost library location and it works.

**Comment by mclow** [comment]
So I should mark this issue as resolved?

**Comment by nghia1303** [comment]
@mclow yeah, i think
