### ISSUE TITLE
On windows b2 --help prints wrong text.

### ISSUE THREAD

**Issue by nanoric** [boostorg/boost#959]
On Windows, b2 --help says:
```
  --prefix=<PREFIX>       Install architecture independent files here.
                          Default: C:\Boost on Windows
                          Default: /usr/local on Unix, Linux, etc.
```
But if the user calls ```b2 install```, only ```C:\Boost\include``` will be installed. The libraries will not be installed into ```C:\Boost\lib```.

Only by calling ```b2 --prefix=C:\Boost install``` will both headers and libraries be installed correctly.

**Comment by thtrummer** [comment]
The help text is actually correct, it just has been broken for the last few releases.
